@startuml
class Quiz {
-{static}ArrayList<Question> questionList
+{static}QuizFrame quizFrame
-{static}int QuestionIndex
-boolean joker
-int score
--
..Konstruktor..
+Quiz(String gameMode)
..Getter-Funktionen..
+boolean getJoker()
..Setter-Funktionen..
+void setJoker(boolean joker)
+void addScore()
+void addQuestion(Question question)
..
+void start()
+void nextQuestion()
+void finish()
-void shuffleQuestions()
-void loadQuestionsFromJson()
-void saveQuestionsToJson()
}
@enduml